/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasikalkulator;

/**
 *
 * @author Entrihestia
 */
public class AplikasiKalkulatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiKalkulatorGUI
     */
    public AplikasiKalkulatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        InputKalkulator = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        VariabelDesimal = new javax.swing.JButton();
        VariabelAngka0 = new javax.swing.JButton();
        VariabelAngka1 = new javax.swing.JButton();
        VariabelAngka2 = new javax.swing.JButton();
        VariabelAngka3 = new javax.swing.JButton();
        VariabelAngka4 = new javax.swing.JButton();
        VariabelAngka5 = new javax.swing.JButton();
        VariabelAngka6 = new javax.swing.JButton();
        VariabelAngka7 = new javax.swing.JButton();
        VariabelAngka8 = new javax.swing.JButton();
        VariabelAngka9 = new javax.swing.JButton();
        VariabelClear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        VariabelBackspace = new javax.swing.JButton();
        VariabelExponential = new javax.swing.JButton();
        VariabelSamaDengan = new javax.swing.JButton();
        VariabelPersentase = new javax.swing.JButton();
        VariabelPerkalian = new javax.swing.JButton();
        VariabelPembagian = new javax.swing.JButton();
        VariabelTambah = new javax.swing.JButton();
        VariabelPengurangan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        InputKalkulator.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(InputKalkulator, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputKalkulator, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        VariabelDesimal.setText(".");
        VariabelDesimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelDesimalActionPerformed(evt);
            }
        });

        VariabelAngka0.setText("0");
        VariabelAngka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelAngka0ActionPerformed(evt);
            }
        });

        VariabelAngka1.setText("1");
        VariabelAngka1.setToolTipText("");
        VariabelAngka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelAngka1ActionPerformed(evt);
            }
        });

        VariabelAngka2.setText("2");
        VariabelAngka2.setToolTipText("");
        VariabelAngka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelAngka2ActionPerformed(evt);
            }
        });

        VariabelAngka3.setText("3");
        VariabelAngka3.setToolTipText("");
        VariabelAngka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelAngka3ActionPerformed(evt);
            }
        });

        VariabelAngka4.setText("4");
        VariabelAngka4.setToolTipText("");
        VariabelAngka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelAngka4ActionPerformed(evt);
            }
        });

        VariabelAngka5.setText("5");
        VariabelAngka5.setToolTipText("");
        VariabelAngka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelAngka5ActionPerformed(evt);
            }
        });

        VariabelAngka6.setText("6");
        VariabelAngka6.setToolTipText("");
        VariabelAngka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelAngka6ActionPerformed(evt);
            }
        });

        VariabelAngka7.setText("7");
        VariabelAngka7.setToolTipText("");
        VariabelAngka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelAngka7ActionPerformed(evt);
            }
        });

        VariabelAngka8.setText("8");
        VariabelAngka8.setToolTipText("");
        VariabelAngka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelAngka8ActionPerformed(evt);
            }
        });

        VariabelAngka9.setText("9");
        VariabelAngka9.setToolTipText("");
        VariabelAngka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelAngka9ActionPerformed(evt);
            }
        });

        VariabelClear.setText("C");
        VariabelClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(VariabelAngka7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VariabelAngka8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VariabelAngka9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(VariabelAngka4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VariabelAngka5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VariabelAngka6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(VariabelDesimal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VariabelAngka0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VariabelClear, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(VariabelAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VariabelAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VariabelAngka3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VariabelAngka7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelAngka8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelAngka9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VariabelAngka6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelAngka5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelAngka4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VariabelAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelAngka3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VariabelDesimal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelAngka0, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelClear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        VariabelBackspace.setText("B");
        VariabelBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelBackspaceActionPerformed(evt);
            }
        });

        VariabelExponential.setText("E");
        VariabelExponential.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelExponentialActionPerformed(evt);
            }
        });

        VariabelSamaDengan.setText("=");
        VariabelSamaDengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelSamaDenganActionPerformed(evt);
            }
        });

        VariabelPersentase.setText("%");
        VariabelPersentase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelPersentaseActionPerformed(evt);
            }
        });

        VariabelPerkalian.setText("*");
        VariabelPerkalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelPerkalianActionPerformed(evt);
            }
        });

        VariabelPembagian.setText("/");
        VariabelPembagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelPembagianActionPerformed(evt);
            }
        });

        VariabelTambah.setText("+");
        VariabelTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelTambahActionPerformed(evt);
            }
        });

        VariabelPengurangan.setText("-");
        VariabelPengurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariabelPenguranganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(VariabelTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelPerkalian, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VariabelExponential, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelPersentase, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelPembagian, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelPengurangan, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VariabelTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelPengurangan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VariabelPerkalian, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelPembagian, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VariabelSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelPersentase, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VariabelBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VariabelExponential, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jLabel1.setText("Aplikasi Kalkulator");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private double angkaPertama = 0;
private double angkaKedua = 0;
private String operator = "";

    private void VariabelDesimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelDesimalActionPerformed
            if (!InputKalkulator.getText().contains(".")) {
        InputKalkulator.setText(InputKalkulator.getText() + ".");
        }
    }//GEN-LAST:event_VariabelDesimalActionPerformed

    private void VariabelAngka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelAngka0ActionPerformed
         InputKalkulator.setText(InputKalkulator.getText() + "0");
    }//GEN-LAST:event_VariabelAngka0ActionPerformed

    private void VariabelAngka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelAngka2ActionPerformed
         InputKalkulator.setText(InputKalkulator.getText() + "2");
    }//GEN-LAST:event_VariabelAngka2ActionPerformed

    private void VariabelAngka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelAngka1ActionPerformed
         InputKalkulator.setText(InputKalkulator.getText() + "1");
    }//GEN-LAST:event_VariabelAngka1ActionPerformed

    private void VariabelAngka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelAngka3ActionPerformed
         InputKalkulator.setText(InputKalkulator.getText() + "3");
    }//GEN-LAST:event_VariabelAngka3ActionPerformed

    private void VariabelAngka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelAngka4ActionPerformed
         InputKalkulator.setText(InputKalkulator.getText() + "4");
    }//GEN-LAST:event_VariabelAngka4ActionPerformed

    private void VariabelAngka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelAngka5ActionPerformed
         InputKalkulator.setText(InputKalkulator.getText() + "5");
    }//GEN-LAST:event_VariabelAngka5ActionPerformed

    private void VariabelAngka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelAngka6ActionPerformed
         InputKalkulator.setText(InputKalkulator.getText() + "6");
    }//GEN-LAST:event_VariabelAngka6ActionPerformed

    private void VariabelAngka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelAngka7ActionPerformed
         InputKalkulator.setText(InputKalkulator.getText() + "7");
    }//GEN-LAST:event_VariabelAngka7ActionPerformed

    private void VariabelAngka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelAngka8ActionPerformed
         InputKalkulator.setText(InputKalkulator.getText() + "8");
    }//GEN-LAST:event_VariabelAngka8ActionPerformed

    private void VariabelAngka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelAngka9ActionPerformed
         InputKalkulator.setText(InputKalkulator.getText() + "9");
    }//GEN-LAST:event_VariabelAngka9ActionPerformed

    private void VariabelBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelBackspaceActionPerformed
         String currentText = InputKalkulator.getText();
           if (!currentText.isEmpty()) {
            InputKalkulator.setText(currentText.substring(0, currentText.length() - 1));
        }
    }//GEN-LAST:event_VariabelBackspaceActionPerformed

    private void VariabelExponentialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelExponentialActionPerformed
        angkaPertama = Double.parseDouble(InputKalkulator.getText());
        operator = "exp";
        InputKalkulator.setText("");
    }//GEN-LAST:event_VariabelExponentialActionPerformed

    private void VariabelSamaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelSamaDenganActionPerformed
        angkaKedua = Double.parseDouble(InputKalkulator.getText());
    double hasil = 0;
    
    switch (operator) {
        case "+" -> hasil = angkaPertama + angkaKedua;
        case "-" -> hasil = angkaPertama - angkaKedua;
        case "*" -> hasil = angkaPertama * angkaKedua;
        case "/" -> {
            if (angkaKedua != 0) {
                hasil = angkaPertama / angkaKedua;
            } else {
                InputKalkulator.setText("Error");
                return;
            }
            }
        case "exp" -> hasil = Math.pow(angkaPertama, angkaKedua);
        case "%" -> hasil = angkaPertama % angkaKedua;
    }
    
    InputKalkulator.setText(String.valueOf(hasil));
    }//GEN-LAST:event_VariabelSamaDenganActionPerformed

    private void VariabelPersentaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelPersentaseActionPerformed
        angkaPertama = Double.parseDouble(InputKalkulator.getText());
        operator = "%";
        InputKalkulator.setText("");
    }//GEN-LAST:event_VariabelPersentaseActionPerformed

    private void VariabelPerkalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelPerkalianActionPerformed
        angkaPertama = Double.parseDouble(InputKalkulator.getText());
        operator = "*";
        InputKalkulator.setText("");
    }//GEN-LAST:event_VariabelPerkalianActionPerformed

    private void VariabelPembagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelPembagianActionPerformed
        angkaPertama = Double.parseDouble(InputKalkulator.getText());
        operator = "/";
        InputKalkulator.setText("");
    }//GEN-LAST:event_VariabelPembagianActionPerformed

    private void VariabelTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelTambahActionPerformed
        angkaPertama = Double.parseDouble(InputKalkulator.getText());
        operator = "+";
        InputKalkulator.setText("");
    }//GEN-LAST:event_VariabelTambahActionPerformed

    private void VariabelPenguranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelPenguranganActionPerformed
        angkaPertama = Double.parseDouble(InputKalkulator.getText());
        operator = "-";
        InputKalkulator.setText("");
    }//GEN-LAST:event_VariabelPenguranganActionPerformed

    private void VariabelClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariabelClearActionPerformed
        InputKalkulator.setText("");
        angkaPertama = 0;
        angkaKedua = 0;
        operator = "";
    }//GEN-LAST:event_VariabelClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AplikasiKalkulatorGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputKalkulator;
    private javax.swing.JButton VariabelAngka0;
    private javax.swing.JButton VariabelAngka1;
    private javax.swing.JButton VariabelAngka2;
    private javax.swing.JButton VariabelAngka3;
    private javax.swing.JButton VariabelAngka4;
    private javax.swing.JButton VariabelAngka5;
    private javax.swing.JButton VariabelAngka6;
    private javax.swing.JButton VariabelAngka7;
    private javax.swing.JButton VariabelAngka8;
    private javax.swing.JButton VariabelAngka9;
    private javax.swing.JButton VariabelBackspace;
    private javax.swing.JButton VariabelClear;
    private javax.swing.JButton VariabelDesimal;
    private javax.swing.JButton VariabelExponential;
    private javax.swing.JButton VariabelPembagian;
    private javax.swing.JButton VariabelPengurangan;
    private javax.swing.JButton VariabelPerkalian;
    private javax.swing.JButton VariabelPersentase;
    private javax.swing.JButton VariabelSamaDengan;
    private javax.swing.JButton VariabelTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
